systemctl enable NetworkManager
systemctl enable bluetooth
systemctl enable sshd
systemctl enable tlp
systemctl enable firewalld
systemctl enable acpid
systemctl enable fstrim.timer
systemctl enable reflector.timer
systemctl enable avahi-daemon
